VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IContainer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Property Get Page() As Long

End Property

Property Get Rotation() As Long

End Property

Property Get hDC() As Long

End Property

Property Get Width() As Long

End Property

Property Get Height() As Long

End Property

Public Function ImageToScreen(v As CRect) As CRect

End Function

Property Let ForeColor(v As Long)

End Property

Property Let DrawMode(v As Long)

End Property

