VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "INavigator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Sub Update()

End Sub

Public Sub UpdateEx(Left As Long, Top As Long, Width As Long, Height As Long)

End Sub

Property Get Top() As Long

End Property

Property Let Top(v As Long)

End Property

Property Get Left() As Long

End Property

Property Let Left(v As Long)

End Property

Public Sub SetTarget(v As INavigatorEvents)

End Sub

